In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('covid_toy.csv')

In [9]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

age is continuos data, gender is categorical data ,
fever is continuous data, cough is categorical
city is categorical data -> nominal, has_covid is categorical -> nominal data
target is label encoder, has_covid (label encodur)

In [10]:
# can see unique data
df['cough'].unique()

array(['Mild', 'Strong'], dtype=object)

In [11]:
df.isnull().sum() # checking is missing value

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [13]:
df.shape

(100, 6)

In [14]:
from sklearn.model_selection import train_test_split

x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [15]:
X_train, X_test,Y_train,Y_test = train_test_split(x,y,test_size= 0.2, random_state=40)

random_state can not change data sequence

In [16]:
X_train

    age  gender  fever   cough       city
72   83  Female  101.0    Mild    Kolkata
66   51    Male  104.0    Mild    Kolkata
69   73  Female  103.0    Mild      Delhi
67   65    Male   99.0    Mild  Bangalore
26   19  Female  100.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
56   71    Male    NaN  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata
7    20  Female    NaN  Strong     Mumbai
91   38    Male    NaN    Mild      Delhi
70   68  Female  101.0  Strong      Delhi

[80 rows x 5 columns]

In [17]:
X_train.shape

(80, 5)

In [18]:
X_test.shape

(20, 5)

In [19]:
Y_train.shape

(80,)